version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./projecthack:/app
    environment:
      - PYTHONUNBUFFERED=1
    privileged: true

  frontend: # Фронтенд
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./signal-frontend:/app